import { Category, Product, DeliveryZoneOption } from '@/types';

export const BRAND_INFO = {
  name: 'NAQSH by Farjana',
  tagline: 'Timeless Elegance & Bespoke Artisanal Fashion',
  description:
    'Exquisite handcrafted sarees, designer three-piece salwar suits, royal bridal ensembles, and contemporary ethnic wear curated by Farjana.',
  facebookUrl: 'https://www.facebook.com/NAQSH.by.Farjana/',
  facebookPageId: 'NAQSH.by.Farjana',
  messengerUrl: 'https://m.me/NAQSH.by.Farjana',
  whatsappNumber: '+8801580254707',
  whatsappDisplay: '+880 1580-254707',
  phone: '+880 1580-254707',
  email: 'contact@naqshbyfarjana.com',
  address: 'Banani & Dhanmondi Studio, Dhaka, Bangladesh',
  bkashNumber: '01580254707 (Merchant / Send Money)',
  nagadNumber: '01580254707 (Personal)',
  currency: '৳',
};

export const DELIVERY_ZONES: DeliveryZoneOption[] = [
  {
    id: 'inside_dhaka',
    name: 'Inside Dhaka City',
    fee: 80,
    estimated_days: '1-2 Days',
  },
  {
    id: 'dhaka_suburbs',
    name: 'Dhaka Suburbs (Gazipur, Savar, Narayanganj, Keraniganj)',
    fee: 120,
    estimated_days: '2-3 Days',
  },
  {
    id: 'outside_dhaka',
    name: 'Outside Dhaka (All Over Bangladesh)',
    fee: 150,
    estimated_days: '3-5 Days (SteadFast / Pathao / RedX)',
  },
];

export const CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Morja Collection',
    slug: 'morja',
    description: 'Luxury digital lawn 3-piece sets with embroidered organza necklines & pure chiffon dupattas.',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
    item_count: 6,
  },
  {
    id: 'cat-2',
    name: 'Gul Banu Collection',
    slug: 'gul-banu',
    description: 'Festive cotton silk, delicate zardozi work, and handcrafted organza 3-piece ensembles.',
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
    item_count: 5,
  },
  {
    id: 'cat-3',
    name: 'Noor-E-Jahan Edition',
    slug: 'noor-e-jahan',
    description: 'Opulent raw silk suits and royal partywear adorned with traditional tilla & dabka embroidery.',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
    item_count: 4,
  },
  {
    id: 'cat-4',
    name: 'Heritage Sarees',
    slug: 'sarees',
    description: 'Handwoven 84-count Dhakai Jamdani, pure Bengal Muslin, and heirloom Katan Silk masterworks.',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    item_count: 8,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Heritage Crimson Dhakai Jamdani Saree',
    slug: 'heritage-crimson-dhakai-jamdani-saree',
    description:
      'Masterpiece 84-count pure cotton Dhakai Jamdani hand-woven by national heritage weavers in Rupganj. Embellished with all-over intricate gold zari floral jaal and traditional paisley (kalka) pallu. Breathable, featherlight, and timeless.',
    price: 14500,
    original_price: 16800,
    category: 'Heritage Sarees',
    category_slug: 'sarees',
    fabric: 'Pure Dhakai Cotton & Resham Zari',
    color: 'Royal Crimson & Gold',
    sizes: ['Free Size (6.5 Yards with Blouse Piece)'],
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=900&q=80',
    ],
    in_stock: true,
    stock_count: 6,
    is_featured: true,
    is_bestseller: true,
    is_new_arrival: true,
    sku: 'NQ-SR-0101',
    details: [
      'Authentic Bangladeshi Handloom Craft',
      'Includes unstitched matching running blouse piece (80cm)',
      '100% Hand-woven motif detailing',
      'Featherweight luxury drape',
    ],
    care_instructions: [
      'Strictly Dry Clean Only',
      'Store wrapped in pure cotton muslin cloth',
      'Do not machine wash or direct sunlight dry',
    ],
  },
  {
    id: 'prod-2',
    title: 'Morja Luxury Embroidered Lawn 3-Piece Suit',
    slug: 'morja-luxury-embroidered-lawn-3-piece-suit',
    description:
      'From NAQSH’s signature Morja collection. Premium high-density luxury lawn shirt with heavy embroidered organza neckline, tilla threadwork lace borders, dyed cambric cotton trousers, and a digital printed pure silk chiffon dupatta.',
    price: 6850,
    original_price: 8200,
    category: 'Morja Collection',
    category_slug: 'morja',
    fabric: 'Luxury Lawn, Organza Lace & Pure Chiffon Dupatta',
    color: 'Emerald & Sage Floral',
    sizes: ['Unstitched (3-Piece Fabric)', 'Stitched S (36)', 'Stitched M (38)', 'Stitched L (40)', 'Stitched XL (42)'],
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=80',
    ],
    in_stock: true,
    stock_count: 12,
    is_featured: true,
    is_bestseller: true,
    is_new_arrival: true,
    sku: 'NQ-MR-0201',
    details: [
      'Signature Morja collection luxury 3-piece',
      'Heavy embroidered front yolk & sleeve organza patches',
      'Digital printed pure chiffon dupatta (2.5 yards)',
      'Premium breathable cotton cambric trousers',
    ],
    care_instructions: [
      'Gentle hand wash with mild detergent or Dry Clean',
      'Iron on low-to-medium heat with pressing cloth',
    ],
  },
  {
    id: 'prod-3',
    title: 'Gul Banu Hand-Embroidered Cotton Silk 3-Piece Set',
    slug: 'gul-banu-hand-embroidered-cotton-silk-3-piece-set',
    description:
      'From NAQSH’s acclaimed Gul Banu festive collection. Exquisite floral resham embroidery on soft cotton silk, adorned with subtle pearl sequin highlights, paired with tailored cigarette pants and a gold-scalloped organza dupatta.',
    price: 7950,
    original_price: 9500,
    category: 'Gul Banu Collection',
    category_slug: 'gul-banu',
    fabric: 'Soft Cotton Silk & Scalloped Organza Dupatta',
    color: 'Pastel Rose & Gold',
    sizes: ['Unstitched (3-Piece)', 'Stitched S (36)', 'Stitched M (38)', 'Stitched L (40)', 'Stitched XL (42)'],
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=900&q=80',
    ],
    in_stock: true,
    stock_count: 9,
    is_featured: true,
    is_bestseller: true,
    is_new_arrival: true,
    sku: 'NQ-GB-0301',
    details: [
      'Signature Gul Banu luxury festive design',
      'Intricate needlework with floral resham threads',
      'Organza dupatta with heavy 4-side laser cut scalloping',
      'Breathable comfortable lining attached in stitched version',
    ],
    care_instructions: [
      'Dry Clean Recommended',
      'Store in provided protective breathable bag',
    ],
  },
  {
    id: 'prod-4',
    title: 'Noor-E-Jahan Royal Zardozi Raw Silk 3-Piece',
    slug: 'noor-e-jahan-royal-zardozi-raw-silk-3-piece',
    description:
      'Luxurious deep ruby raw silk long kameez featuring heavy zardozi neckline, antique tilla threadwork, and cutwork borders. Paired with straight silk trousers and an ethereal organza dupatta with gold scalloped borders.',
    price: 8950,
    original_price: 10500,
    category: 'Noor-E-Jahan Edition',
    category_slug: 'noor-e-jahan',
    fabric: 'Raw Silk Kameez & Trousers, Pure Organza Dupatta',
    color: 'Royal Ruby & Antique Gold',
    sizes: ['S (Bust 36)', 'M (Bust 38)', 'L (Bust 40)', 'XL (Bust 42)', 'XXL (Bust 44)'],
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80',
    ],
    in_stock: true,
    stock_count: 7,
    is_featured: true,
    is_bestseller: true,
    sku: 'NQ-NJ-0401',
    details: [
      'Complete 3-Piece Ready-to-wear set',
      'Fine micro-thread embroidery and stone highlights',
      'Pure inner lining attached for premium finish',
      'Comfortable elasticated waistband with drawstring',
    ],
    care_instructions: [
      'Dry Clean Recommended',
      'Iron on low-to-medium heat with protective pressing cloth',
    ],
  },
  {
    id: 'prod-5',
    title: 'Morja Pastel Mint Chikankari Lawn 3-Piece',
    slug: 'morja-pastel-mint-chikankari-lawn-3-piece',
    description:
      'Subtle mint green luxury lawn 3-piece outfit from Morja edition with intricate all-over chikankari embroidery, gotta-patti lace highlights, matching lawn trousers, and a lightweight printed chiffon dupatta.',
    price: 6450,
    original_price: 7800,
    category: 'Morja Collection',
    category_slug: 'morja',
    fabric: 'Chikankari Lawn & Printed Chiffon',
    color: 'Pastel Mint Green',
    sizes: ['Unstitched (3-Piece)', 'Stitched S (36)', 'Stitched M (38)', 'Stitched L (40)', 'Stitched XL (42)'],
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=900&q=80',
    ],
    in_stock: true,
    stock_count: 14,
    is_featured: false,
    is_new_arrival: true,
    sku: 'NQ-MR-0202',
    details: [
      'Morja premium lawn with fine chikankari motifs',
      'Pre-shrunk colorfast fabric',
      'Includes printed chiffon dupatta and solid dyed bottom',
    ],
    care_instructions: ['Gentle hand wash in cold water', 'Medium iron'],
  },
  {
    id: 'prod-6',
    title: 'Banarasi Katan Silk Antique Gold Saree',
    slug: 'banarasi-katan-silk-antique-gold-saree',
    description:
      'Pure heavy Katan Silk saree woven with intricate antique gold zari jangla work, rich minakari motifs on the border, and an opulent grand aanchal.',
    price: 18500,
    original_price: 22000,
    category: 'Heritage Sarees',
    category_slug: 'sarees',
    fabric: '100% Pure Katan Silk',
    color: 'Deep Teal & Antique Gold',
    sizes: ['Free Size (6.5 Yards with Blouse Piece)'],
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=900&q=80',
    ],
    in_stock: true,
    stock_count: 5,
    is_featured: true,
    sku: 'NQ-SR-0108',
    details: [
      'Silk Mark Certified Authenticity',
      'Rich contrast brocade blouse piece included',
      'Heirloom bridal quality',
    ],
    care_instructions: ['Dry Clean Only', 'Wrap in muslin cloth and air dry in shade periodically'],
  },
  {
    id: 'prod-7',
    title: 'Morja Midnight Blue Digital Lawn 3-Piece Suit',
    slug: 'morja-midnight-blue-digital-lawn-3-piece-suit',
    description:
      'Stunning Morja edition luxury lawn three-piece suit in midnight royal blue with metallic tilla embroidery on neckline, organza sleeve borders, tailored cotton trousers, and a digital printed luxury chiffon dupatta.',
    price: 6950,
    original_price: 8400,
    category: 'Morja Collection',
    category_slug: 'morja',
    fabric: 'Digital Printed Luxury Lawn & Silk Chiffon',
    color: 'Midnight Royal Blue & Gold',
    sizes: ['Unstitched (3-Piece)', 'Stitched S (36)', 'Stitched M (38)', 'Stitched L (40)', 'Stitched XL (42)'],
    images: [
      'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=80',
    ],
    in_stock: true,
    stock_count: 8,
    is_featured: false,
    is_bestseller: true,
    sku: 'NQ-MR-0203',
    details: [
      'Morja luxury festive collection',
      'Digital printed lawn shirt with resham threadwork patch',
      'Matching solid dyed breathable trousers',
      'Pure silk chiffon dupatta (2.5 yards)',
    ],
    care_instructions: ['Gentle Hand Wash or Dry Clean', 'Steam Iron'],
  },
  {
    id: 'prod-8',
    title: 'Gul Banu Dusty Peach Embroidered Festive Suit',
    slug: 'gul-banu-dusty-peach-embroidered-festive-suit',
    description:
      'Exclusive Gul Banu edition 3-piece suit in dusty peach organza with intricate dabka neckline, gotta patti work, paired with cigarette trousers and a heavily embroidered scalloped border dupatta.',
    price: 8450,
    original_price: 9900,
    category: 'Gul Banu Collection',
    category_slug: 'gul-banu',
    fabric: 'Pure Organza, Shantoon Inner, Net Dupatta',
    color: 'Dusty Peach & Rose Gold',
    sizes: ['Unstitched (3-Piece)', 'Stitched S (36)', 'Stitched M (38)', 'Stitched L (40)', 'Stitched XL (42)'],
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80',
    ],
    in_stock: true,
    stock_count: 10,
    is_featured: true,
    is_new_arrival: true,
    sku: 'NQ-GB-0302',
    details: [
      'Gul Banu festive boutique edition',
      'Includes matching bottom and embroidered dupatta',
      'Full inner lining attached in stitched version',
    ],
    care_instructions: ['Dry Clean Only', 'Store on padded hanger'],
  },
];
